# EDA DE DATASET DE DATOS ABIERTOS(INGRESANTES A LA UNI)
## DATASET : https://www.datosabiertos.gob.pe/dataset/postulantes-al-concurso-de-admisi%C3%B3n-de-la-universidad-nacional-de-ingenier%C3%ADa-uni

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
PATH_CSV = '/content/drive/MyDrive/NOTEBOOKS/MODULO9/DATASETS/Datos_abiertos_admision_2021_1_2024_1.csv'

In [3]:
df = pd.read_csv(PATH_CSV)
df

,IDHASH,COLEGIO,COLEGIO_DEPA,COLEGIO_PROV,COLEGIO_DIST,COLEGIO_PAIS,COLEGIO_ANIO_EGRESO,ESPECIALIDAD,ANIO_POSTULA,CICLO_POSTULA,...,DOMICILIO_DIST,ANIO_NACIMIENTO,NACIMIENTO_PAIS,NACIMIENTO_DEPA,NACIMIENTO_PROV,NACIMIENTO_DIST,SEXO,CALIF_FINAL,INGRESO,MODALIDAD
0,E4287C2FE19F63C5E6641955147E36684A5A2FF8064676...,LA DIVINA PROVIDENCIA,LIMA,LIMA,SURQUILLO,PERÚ,2020,INGENIERÍA DE SISTEMAS,2021,1,...,SAN JUAN DE MIRAFLORES,2004,PERÚ,LIMA,LIMA,VILLA EL SALVADOR,MASCULINO,3.110,NO,EXTRAORDINARIO1 - DEPORTISTAS CALIFICADOS DE A...
1,2DC37F0B9727B6591EC72D7A942647797A200F45D47C9E...,86019 LA LIBERTAD,ÁNCASH,HUARAZ,HUARAZ,PERÚ,2017,INGENIERÍA DE TELECOMUNICACIONES,2021,1,...,HUARAZ,2001,PERÚ,ÁNCASH,HUARAZ,HUARAZ,FEMENINO,3.580,NO,ORDINARIO
2,3B8677B90781D7BB8F2F967C05FA2DBBE153BBB682DF05...,0113 DANIEL ALOMIAS ROBLES,LIMA,LIMA,SAN JUAN DE LURIGANCHO,PERÚ,2016,INGENIERÍA MECÁNICA,2021,1,...,SAN JUAN DE LURIGANCHO,2000,PERÚ,LIMA,LIMA,JESÚS MARÍA,MASCULINO,8.040,NO,ORDINARIO
3,FA366704D9E9F6FB5E5F55C1FB0CEEE973C626A5616F55...,SEBASTIAN SALAZAR BONDY,LIMA,LIMA,SANTA ANITA,PERÚ,2018,INGENIERÍA ELECTRÓNICA,2021,1,...,SANTA ANITA,2002,PERÚ,LIMA,LIMA,LIMA,MASCULINO,10.820,NO,EXTRAORDINARIO2 – INGRESO DIRECTO CEPRE
4,E31CF8F30F3AE60B3D8A14F6E1020E9AD26EE975F0823B...,TRILCE LOS OLIVOS,LIMA,LIMA,SAN MARTÍN DE PORRES,PERÚ,2020,ARQUITECTURA,2021,1,...,INDEPENDENCIA,2004,PERÚ,LIMA,LIMA,COMAS,FEMENINO,6.210,NO,ORDINARIO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42511,370728AB03E7ECDE69265AC64B0A682887B0BA3E40644F...,BARTOLOME HERRERA,LIMA,LIMA,SAN MIGUEL,NaN,2019,INGENIERÍA CIVIL,2023,1,...,LA PERLA,2002,PERÚ,CALLAO,PROV CONST DEL CALLAO,BELLAVISTA,MASCULINO,5.906,NO,ORDINARIO
42512,C03C7AC74210DA0F4862BFEDAE45CF3BB5AE9813FCF409...,FE Y ALEGRIA 59,CALLAO,PROV CONST DEL CALLAO,VENTANILLA,NaN,2021,INGENIERÍA CIVIL,2023,1,...,VENTANILLA,2004,PERÚ,CALLAO,PROV CONST DEL CALLAO,CALLAO,FEMENINO,2.621,NO,ORDINARIO
42513,E6337F43BAEF0F59EDF11F6F16A47A908717DE288B7886...,CIENCIAS,AYACUCHO,HUAMANGA,SAN JUAN BAUTISTA,NaN,2022,ARQUITECTURA,2023,1,...,AYACUCHO,2006,PERÚ,AYACUCHO,HUAMANGA,AYACUCHO,FEMENINO,7.974,NO,ORDINARIO
42514,13F7CD09C661B02F61218445885DA7C4FDBD87392F7522...,SAN CARLOS,LIMA,LIMA,LURIGANCHO,NaN,2021,ARQUITECTURA,2023,1,...,LURIGANCHO,2004,PERÚ,LIMA,LIMA,MIRAFLORES,FEMENINO,9.477,NO,ORDINARIO
42515,89BFAB90B1C8C25D61557264958F988E305385A9351B5C...,TRILCE SAN JUAN,LIMA,LIMA,SAN JUAN DE LURIGANCHO,NaN,2021,INGENIERÍA DE SISTEMAS,2023,1,...,SAN JUAN DE LURIGANCHO,2005,PERÚ,LIMA,LIMA,SAN JUAN DE LURIGANCHO,MASCULINO,7.228,NO,ORDINARIO

In [8]:
df['MODALIDAD'].value_counts()

MODALIDAD
ORDINARIO                                                                                            24054
INGRESO ESCOLAR NACIONAL                                                                              7245
EXTRAORDINARIO 2 – INGRESO DIRECTO CEPRE                                                              3666
EXTRAORDINARIO INGRESO DIRECTO CEPRE-UNI                                                              3178
EXTRAORDINARIO INGRESO DIRECTO CEPRE-UNI O CEPRE-UNI INTENSIVO                                        1405
EXTRAORDINARIO2 – INGRESO DIRECTO CEPRE                                                                930
TALENTO BECA 18                                                                                        397
EXTRAORDINARIO - DOS PRIMEROS ALUMNOS                                                                  298
EXTRAORDINARIO 1 - DOS PRIMEROS ALUMNOS                                                                279
EXTRAORDINARIO1 - DOS PRIMEROS ALUMNOS                                                                 176
EXTRAORDINARIO - VÍCTIMA DEL TERRORISMO (iniciar estudios)                                             127
EXTRAORDINARIO - TRASLADO EXTERNO                                                                      122
EXTRAORDINARIO 1 - VÍCTIMA DEL TERRORISMO (iniciar estudios)                                           111
EXTRAORDINARIO 1 - TRASLADO EXTERNO                                                                     60
EXTRAORDINARIO - TITULADOS O GRADUADOS EN OTRA UNIVERSIDAD                                              55
INTERESADO                                                                                              55
EXTRAORDINARIO 1 - TITULADO O GRADUADO UNI                                                              47
EXTRAORDINARIO1 - VICTIMAS DEL TERRORISMO (iniciar estudios)                                            43
EXTRAORDINARIO - TITULADOS O GRADUADOS UNI                                                              41
EXTRAORDINARIO 1 - TITULADOS O GRADUADOS EN OTRA UNIVERSIDAD                                            30
EXTRAORDINARIO1 - TRASLADO EXTERNO                                                                      24
EXTRAORDINARIO 1 - DIPLOMADOS CON BACHILLERATO INTERNACIONAL                                            22
EXTRAORDINARIO1 - TITULADO O GRADUADO UNI                                                               20
EXTRAORDINARIO - DIPLOMADO CON BACHILLERATO INTERNACIONAL                                               18
EXTRAORDINARIO1 - DIPLOMADOS CON BACHILLERATO                                                           16
EXTRAORDINARIO2 - TALENTO BECA 18                                                                       16
EXTRAORDINARIO - PERSONA CON DISCAPACIDAD (iniciar estudios)                                            14
EXTRAORDINARIO 1 - DIPLOMADOS CON BACHILLERATO                                                           8
EXTRAORDINARIO1 - TITULADOS O GRADUADOS                                                                  8
EXTRAORDINARIO 1 - PERSONAS CON DISCAPACIDAD (iniciar estudios)                                          7
EXTRAORDINARIO - VICTIMA DEL TERRORISMO (continuar estudios)                                             6
EXTRAORDINARIO 1 - DEPORTISTAS CALIFICADOS DE ALTO NIVEL( Iniciar estudios)                              5
EXTRAORDINARIO 1 - TRASLADO EXTERNO PARA ESTUDIANTES PROVENIENTES DE UNIVERSIDADES NO LICENCIADAS        5
EXTRAORDINARIO 1 - VICTIMAS DEL TERRORISMO (continuar estudios)                                          4
EXTRAORDINARIO - DEPORTISTA CALIFICADO DE ALTO NIVEL( Iniciar estudios)                                  4
EXTRAORDINARIO1 - VICTIMAS DEL TERRORISMO (continuar estudios)                                           3
EXTRAORDINARIO 1 - CONVENIO ANDRÉS BELLO (iniciar estudios)                                              3
EXTRAORDINARIO1 - DEPORTISTAS CALIFICADOS DE ALTO NIVEL( Iniciar estudios)                               2
EXTRAORDINARIO1 - CONVENIO ANDRES BELLO (iniciar estudios)                                               2
EXTRAORDINARIO - TRASLADO EXTERNO PARA ESTUDIANTES PROVENIENTES DE UNIVERSIDADES NO LICENCIADAS          2
EXTRAORDINARIO1 - CONVENIO ANDRES BELLO (continuar estudios)                                             2
EXTRAORDINARIO1 - TRASLADO EXTERNO PARA ESTUDIANTES PROVENIENTES DE UNIVERSIDADES NO LICENCIADAS         2
EXTRAORDINARIO1 - PERSONAS CON DISCAPACIDAD (iniciar estudios)                                           2
EXTRAORDINARIO 1 - CONVENIO ANDRÉS BELLO (continuar estudios)                                            1
EXTRAORDINARIO 1 - CONVENIO DIPLOMATICO                                                                  1
Name: count, dtype: int64

# EDA

In [4]:
df.dtypes

IDHASH                  object
COLEGIO                 object
COLEGIO_DEPA            object
COLEGIO_PROV            object
COLEGIO_DIST            object
COLEGIO_PAIS            object
COLEGIO_ANIO_EGRESO      int64
ESPECIALIDAD            object
ANIO_POSTULA             int64
CICLO_POSTULA            int64
DOMICILIO_DEPA          object
DOMICILIO_PROV          object
DOMICILIO_DIST          object
ANIO_NACIMIENTO          int64
NACIMIENTO_PAIS         object
NACIMIENTO_DEPA         object
NACIMIENTO_PROV         object
NACIMIENTO_DIST         object
SEXO                    object
CALIF_FINAL            float64
INGRESO                 object
MODALIDAD               object
dtype: object

In [9]:
df_cleaned = df.drop(columns=['IDHASH', 'COLEGIO', 'COLEGIO_PROV','COLEGIO_DIST','COLEGIO_PAIS','DOMICILIO_DEPA','DOMICILIO_PROV','DOMICILIO_DIST','NACIMIENTO_PAIS','NACIMIENTO_DEPA','NACIMIENTO_PROV','NACIMIENTO_DIST','CALIF_FINAL','MODALIDAD'])
df_cleaned

,COLEGIO_DEPA,COLEGIO_ANIO_EGRESO,ESPECIALIDAD,ANIO_POSTULA,CICLO_POSTULA,ANIO_NACIMIENTO,SEXO,INGRESO
0,LIMA,2020,INGENIERÍA DE SISTEMAS,2021,1,2004,MASCULINO,NO
1,ÁNCASH,2017,INGENIERÍA DE TELECOMUNICACIONES,2021,1,2001,FEMENINO,NO
2,LIMA,2016,INGENIERÍA MECÁNICA,2021,1,2000,MASCULINO,NO
3,LIMA,2018,INGENIERÍA ELECTRÓNICA,2021,1,2002,MASCULINO,NO
4,LIMA,2020,ARQUITECTURA,2021,1,2004,FEMENINO,NO
...,...,...,...,...,...,...,...,...
42511,LIMA,2019,INGENIERÍA CIVIL,2023,1,2002,MASCULINO,NO
42512,CALLAO,2021,INGENIERÍA CIVIL,2023,1,2004,FEMENINO,NO
42513,AYACUCHO,2022,ARQUITECTURA,2023,1,2006,FEMENINO,NO
42514,LIMA,2021,ARQUITECTURA,2023,1,2004,FEMENINO,NO
42515,LIMA,2021,INGENIERÍA DE SISTEMAS,2023,1,2005,MASCULINO,NO

In [10]:
df_cleaned['egreso_postulacion'] = df_cleaned['ANIO_POSTULA'] - df_cleaned['COLEGIO_ANIO_EGRESO']
df_cleaned['edad'] = df_cleaned['ANIO_POSTULA'] - df_cleaned['ANIO_NACIMIENTO']
df_cleaned

,COLEGIO_DEPA,COLEGIO_ANIO_EGRESO,ESPECIALIDAD,ANIO_POSTULA,CICLO_POSTULA,ANIO_NACIMIENTO,SEXO,INGRESO,egreso_postulacion,edad
0,LIMA,2020,INGENIERÍA DE SISTEMAS,2021,1,2004,MASCULINO,NO,1,17
1,ÁNCASH,2017,INGENIERÍA DE TELECOMUNICACIONES,2021,1,2001,FEMENINO,NO,4,20
2,LIMA,2016,INGENIERÍA MECÁNICA,2021,1,2000,MASCULINO,NO,5,21
3,LIMA,2018,INGENIERÍA ELECTRÓNICA,2021,1,2002,MASCULINO,NO,3,19
4,LIMA,2020,ARQUITECTURA,2021,1,2004,FEMENINO,NO,1,17
...,...,...,...,...,...,...,...,...,...,...
42511,LIMA,2019,INGENIERÍA CIVIL,2023,1,2002,MASCULINO,NO,4,21
42512,CALLAO,2021,INGENIERÍA CIVIL,2023,1,2004,FEMENINO,NO,2,19
42513,AYACUCHO,2022,ARQUITECTURA,2023,1,2006,FEMENINO,NO,1,17
42514,LIMA,2021,ARQUITECTURA,2023,1,2004,FEMENINO,NO,2,19
42515,LIMA,2021,INGENIERÍA DE SISTEMAS,2023,1,2005,MASCULINO,NO,2,18

In [11]:
df_cleaned = df_cleaned.drop(columns=['COLEGIO_ANIO_EGRESO', 'ANIO_POSTULA', 'CICLO_POSTULA','ANIO_NACIMIENTO'])
df_cleaned

,COLEGIO_DEPA,ESPECIALIDAD,SEXO,INGRESO,egreso_postulacion,edad
0,LIMA,INGENIERÍA DE SISTEMAS,MASCULINO,NO,1,17
1,ÁNCASH,INGENIERÍA DE TELECOMUNICACIONES,FEMENINO,NO,4,20
2,LIMA,INGENIERÍA MECÁNICA,MASCULINO,NO,5,21
3,LIMA,INGENIERÍA ELECTRÓNICA,MASCULINO,NO,3,19
4,LIMA,ARQUITECTURA,FEMENINO,NO,1,17
...,...,...,...,...,...,...
42511,LIMA,INGENIERÍA CIVIL,MASCULINO,NO,4,21
42512,CALLAO,INGENIERÍA CIVIL,FEMENINO,NO,2,19
42513,AYACUCHO,ARQUITECTURA,FEMENINO,NO,1,17
42514,LIMA,ARQUITECTURA,FEMENINO,NO,2,19
42515,LIMA,INGENIERÍA DE SISTEMAS,MASCULINO,NO,2,18

In [12]:
df_cleaned.isnull().sum()

COLEGIO_DEPA          226
ESPECIALIDAD           55
SEXO                    0
INGRESO                 0
egreso_postulacion      0
edad                    0
dtype: int64

In [13]:
df_cleaned = df_cleaned.dropna()
df_cleaned

,COLEGIO_DEPA,ESPECIALIDAD,SEXO,INGRESO,egreso_postulacion,edad
0,LIMA,INGENIERÍA DE SISTEMAS,MASCULINO,NO,1,17
1,ÁNCASH,INGENIERÍA DE TELECOMUNICACIONES,FEMENINO,NO,4,20
2,LIMA,INGENIERÍA MECÁNICA,MASCULINO,NO,5,21
3,LIMA,INGENIERÍA ELECTRÓNICA,MASCULINO,NO,3,19
4,LIMA,ARQUITECTURA,FEMENINO,NO,1,17
...,...,...,...,...,...,...
42511,LIMA,INGENIERÍA CIVIL,MASCULINO,NO,4,21
42512,CALLAO,INGENIERÍA CIVIL,FEMENINO,NO,2,19
42513,AYACUCHO,ARQUITECTURA,FEMENINO,NO,1,17
42514,LIMA,ARQUITECTURA,FEMENINO,NO,2,19
42515,LIMA,INGENIERÍA DE SISTEMAS,MASCULINO,NO,2,18

In [14]:
df_cleaned.to_csv('uni_cleaned.csv',index=None)