# ANALISIS EXPLORATORIO DE DATOS PARA DATASET DE AUTOS EN PERÚ(FUENTE NEOAUTO)

## 1 IMPORTAMOS LIBRERIAS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2 CONECTAMOS A BASE DE DATOS Y CARGAMOS DATASET

In [2]:
from sqlalchemy import create_engine

In [6]:
from google.colab import userdata
conn_string = userdata.get('CON_STR')

In [7]:
# Crear el motor de conexión
try:
    engine = create_engine(conn_string)
    print("Conexión a la base de datos establecida exitosamente.")

    # Cargar la tabla tbl_autos en un DataFrame
    query = "SELECT * FROM tbl_autos"
    df_autos = pd.read_sql(query, engine)

except Exception as e:
    print(f"Error al conectar o cargar datos: {e}")
    engine = None # Asegúrate de que engine sea None si hay un error para evitar problemas posteriores

Conexión a la base de datos establecida exitosamente.

In [8]:
df_autos

,id,title,link,tag,image,fuel,location,price,brand,year,advertiser,category,subcategory,transmission,slug,fecha
0,1854752,volkswagen gol sedán 2021,https://neoauto.com/venta-de-autos-nuevosauto/...,Seminuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Paulo Soto,autos,Sedán,Mecánica,auto/seminuevo/volkswagen-gol-sedan-2021-1854752,2025-11-27 20:06:48.673453
1,1857469,jeep grand cherokee limited 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,Premium,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Auto Traders,autos,Camioneta,Automática - Secuencial,auto/seminuevo/jeep-grand-cherokee-limited-202...,2025-11-27 20:06:48.673453
2,1856331,hyundai tucson 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,Ocasión,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Diego Atoche,autos,Camioneta,Automática,auto/seminuevo/hyundai-tucson-2020-1856331,2025-11-27 20:06:48.673453
3,1817540,mercedes benz amg sl 55 4matic+ 2022,https://neoauto.com/venta-de-autos-nuevosauto/...,Como nuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,sebastian de souza,autos,Deportivo,Automática - Secuencial,auto/seminuevo/mercedes-benz-amg-sl-55-4matic-...,2025-11-27 20:06:48.673453
4,1852040,ford escape 2017,https://neoauto.com/venta-de-autos-nuevosauto/...,Seminuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",13900.0,FORD,2017,Auto Summit San Isidro,autos,Camioneta,Automática - Secuencial,auto/seminuevo/ford-escape-2017-1852040,2025-11-27 20:06:48.673453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4002,1854166,suzuki ertiga 2015,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Geyler Diaz Rivera,autos,Vans,Automática,auto/usado/suzuki-ertiga-2015-1854166,2025-11-27 20:06:48.673453
4003,1856680,mg zs 2018,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",10000.0,MG,2018,Jenniffer Cano,autos,Camioneta,Automática - Secuencial,auto/usado/mg-zs-2018-1856680,2025-11-27 20:06:48.673453
4004,1857073,chevrolet tracker 2024,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Miguel Angel Bernal,autos,Camioneta,Automática,auto/usado/chevrolet-tracker-2024-1857073,2025-11-27 20:06:48.673453
4005,1853868,toyota corolla 2016,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Callao, Callao",13700.0,TOYOTA,2016,Edgar Castro,autos,Sedán,Automática,auto/usado/toyota-corolla-2016-1853868,2025-11-27 20:06:48.673453
4006,1856188,dfsk glory 580 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Dual,"Lima, Lima",15000.0,DFSK,2020,Gustavo guzmán guzmán mazuelos,autos,Camioneta,Automática - Secuencial,auto/usado/dfsk-glory-580-2020-1856188,2025-11-27 20:06:48.673453

In [9]:
df_autos.to_csv('autos.csv',header=None)

# ANALIZAMOS TIPOS DE DATOS Y DATA INNECESARIA

In [10]:
df_autos.dtypes

id                       int64
title                   object
link                    object
tag                     object
image                   object
fuel                    object
location                object
price                  float64
brand                   object
year                     int64
advertiser              object
category                object
subcategory             object
transmission            object
slug                    object
fecha           datetime64[ns]
dtype: object

In [41]:
df_clean = df_autos[['fuel','location','price','brand','year','subcategory','transmission']]
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
1,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Camioneta,Automática - Secuencial
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
3,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,Deportivo,Automática - Secuencial
4,Gasolina,"Lima, Lima",13900.0,FORD,2017,Camioneta,Automática - Secuencial
...,...,...,...,...,...,...,...
4002,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Vans,Automática
4003,Gasolina,"Lima, Lima",10000.0,MG,2018,Camioneta,Automática - Secuencial
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática
4005,Gasolina,"Callao, Callao",13700.0,TOYOTA,2016,Sedán,Automática
4006,Dual,"Lima, Lima",15000.0,DFSK,2020,Camioneta,Automática - Secuencial

### ANALIZAMOS NULOS Y DUPLICADOS

In [42]:
df_clean.isnull().sum()

fuel            0
location        0
price           2
brand           0
year            0
subcategory     0
transmission    0
dtype: int64

In [44]:
df_clean.dropna(inplace=True)

/tmp/ipython-input-1832953665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.dropna(inplace=True)

In [43]:
df_clean.isnull().sum()

fuel            0
location        0
price           2
brand           0
year            0
subcategory     0
transmission    0
dtype: int64

In [45]:
df_clean.duplicated().sum()

np.int64(104)

In [46]:
df_clean.drop_duplicates(inplace=True,keep='first')

/tmp/ipython-input-1033133614.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop_duplicates(inplace=True,keep='first')

In [47]:
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
1,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Camioneta,Automática - Secuencial
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
3,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,Deportivo,Automática - Secuencial
4,Gasolina,"Lima, Lima",13900.0,FORD,2017,Camioneta,Automática - Secuencial
...,...,...,...,...,...,...,...
4002,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Vans,Automática
4003,Gasolina,"Lima, Lima",10000.0,MG,2018,Camioneta,Automática - Secuencial
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática
4005,Gasolina,"Callao, Callao",13700.0,TOYOTA,2016,Sedán,Automática
4006,Dual,"Lima, Lima",15000.0,DFSK,2020,Camioneta,Automática - Secuencial

### ANALIZAMOS LAS VARIABLES CATEGORICAS

In [29]:
# GASOLINA
df_clean['fuel'].value_counts()

fuel
Gasolina            2919
Dual                 319
Diesel               281
Gas GLP              119
Gasolina-Híbrido     118
Gas GNV               58
Híbrido               46
Eléctrico             29
Gas                   12
Name: count, dtype: int64

In [48]:
def map_fuel_type(fuel_type):
    if fuel_type == 'Gasolina':
        return 'gasolina'
    else:
        return 'otro'

df_clean['fuel'] = df_clean['fuel'].apply(map_fuel_type)
df_clean['fuel'].value_counts()

/tmp/ipython-input-2870578674.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['fuel'] = df_clean['fuel'].apply(map_fuel_type)

fuel
gasolina    2919
otro         982
Name: count, dtype: int64

In [49]:
df_clean['location'].value_counts()

location
Lima, Lima                      3489
Arequipa, Arequipa               125
Trujillo, La Libertad             54
Callao, Callao                    35
Piura, Piura                      30
Chiclayo, Lambayeque              23
Cusco, Cusco                      17
Huancayo, Junin                   13
Ica, Ica                          12
Huaraz, Ancash                     8
Chincha, Ica                       8
Tacna, Tacna                       7
Santa, Ancash                      7
Cajamarca, Cajamarca               6
Huanuco, Huanuco                   6
Huamanga, Ayacucho                 5
Huaura, Lima                       4
Cañete, Lima                       3
Islay, Arequipa                    3
Huaral, Lima                       3
San Martin, San Martin             2
Tumbes, Tumbes                     2
Leoncio Prado, Huanuco             2
Pasco, Pasco                       2
Barranca, Lima                     2
Chepen, La Libertad                2
Lambayeque, Lambayeque             2
Pisco, Ica                         2
Puno, Puno                         2
Mariscal Nieto, Moquegua           2
Sechura, Piura                     1
Chanchamayo, Junin                 1
Calca, Cusco                       1
Jaen, Cajamarca                    1
El Dorado, San Martin              1
Caraveli, Arequipa                 1
Nazca, Ica                         1
Yauli, Junin                       1
Chumbivilcas, Cusco                1
Espinar, Cusco                     1
Viru, La Libertad                  1
Pacasmayo, La Libertad             1
Mariscal Caceres, San Martin       1
Huari, Ancash                      1
Concepcion, Junin                  1
Ambo, Huanuco                      1
Sullana, Piura                     1
Abancay, Apurimac                  1
Coronel Portillo, Ucayali          1
Talara, Piura                      1
Paita, Piura                       1
Moyobamba, San Martin              1
San Ignacio, Cajamarca             1
Name: count, dtype: int64

In [50]:
def map_location_type(location):
    if location == 'Lima, Lima':
        return 'lima'
    else:
        return 'provincia'

df_clean['location'] = df_clean['location'].apply(map_location_type)
df_clean['location'].value_counts()

/tmp/ipython-input-3055761826.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['location'] = df_clean['location'].apply(map_location_type)

location
lima         3489
provincia     412
Name: count, dtype: int64

In [51]:
# marcas
df_clean['brand'].value_counts()

brand
BMW           359
TOYOTA        313
VOLKSWAGEN    248
MAZDA         208
NISSAN        204
             ...
HAFEI           1
DATSUN          1
JINBEI          1
JMC             1
BAW             1
Name: count, Length: 70, dtype: int64

In [52]:
df_clean.drop(columns=['brand'], inplace=True)
df_clean.head()

/tmp/ipython-input-3155949640.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(columns=['brand'], inplace=True)

       fuel location     price  year subcategory             transmission
0  gasolina     lima   10900.0  2021       Sedán                 Mecánica
1  gasolina     lima   30990.0  2020   Camioneta  Automática - Secuencial
2  gasolina     lima   19900.0  2020   Camioneta               Automática
3  gasolina     lima  279000.0  2022   Deportivo  Automática - Secuencial
4  gasolina     lima   13900.0  2017   Camioneta  Automática - Secuencial

In [53]:
# year
df_clean['year'].dtype

dtype('int64')

In [54]:
#subcategory
df_clean['subcategory'].value_counts()

subcategory
Camioneta        2293
Sedán             722
Hatchback         372
Pick Up           218
Vans              145
Deportivo         131
Station Wagon      20
Name: count, dtype: int64

In [55]:
def map_subcategory_type(subcategory):
    if subcategory == 'Camioneta':
        return 'camioneta'
    elif subcategory == 'Deportivo':
        return 'deportivo'
    else:
        return 'otros'

df_clean['subcategory'] = df_clean['subcategory'].apply(map_subcategory_type)
df_clean['subcategory'].value_counts()

/tmp/ipython-input-2269517919.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['subcategory'] = df_clean['subcategory'].apply(map_subcategory_type)

subcategory
camioneta    2293
otros        1477
deportivo     131
Name: count, dtype: int64

In [56]:
# transmission
df_clean['transmission'].value_counts()

transmission
Automática - Secuencial    1595
Automática                 1277
Mecánica                   1029
Name: count, dtype: int64

In [57]:
def map_transmission_type(transmission):
    if transmission == 'Automática - Secuencial':
        return 'secuencial'
    elif transmission == 'Automática':
        return 'automatica'
    else:
        return 'mecanica'

df_clean['transmission'] = df_clean['transmission'].apply(map_transmission_type)
df_clean['transmission'].value_counts()

/tmp/ipython-input-875588382.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['transmission'] = df_clean['transmission'].apply(map_transmission_type)

transmission
secuencial    1595
automatica    1277
mecanica      1029
Name: count, dtype: int64

In [58]:
df_clean

          fuel   location     price  year subcategory transmission
0     gasolina       lima   10900.0  2021       otros     mecanica
1     gasolina       lima   30990.0  2020   camioneta   secuencial
2     gasolina       lima   19900.0  2020   camioneta   automatica
3     gasolina       lima  279000.0  2022   deportivo   secuencial
4     gasolina       lima   13900.0  2017   camioneta   secuencial
...        ...        ...       ...   ...         ...          ...
4002  gasolina       lima   11000.0  2015       otros   automatica
4003  gasolina       lima   10000.0  2018   camioneta   secuencial
4004  gasolina       lima   18500.0  2024   camioneta   automatica
4005  gasolina  provincia   13700.0  2016       otros   automatica
4006      otro       lima   15000.0  2020   camioneta   secuencial

[3901 rows x 6 columns]

In [59]:
df_clean.to_csv('autos_clean.csv',index=None)