# ANALISIS EXPLORATORIO DE DATOS PARA DATASET DE AUTOS EN PERÚ(FUENTE NEOAUTO)

## 1 IMPORTAMOS LIBRERIAS

In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2 CONECTAMOS A BASE DE DATOS Y CARGAMOS DATASET

In [61]:
from sqlalchemy import create_engine

In [62]:
from google.colab import userdata
conn_string = userdata.get('CON_STR')

In [77]:
# Crear el motor de conexión
try:
    engine = create_engine(conn_string)
    print("Conexión a la base de datos establecida exitosamente.")

    # Cargar la tabla tbl_autos en un DataFrame
    query = "SELECT * FROM tbl_autos"
    df_autos = pd.read_sql(query, engine)

except Exception as e:
    print(f"Error al conectar o cargar datos: {e}")
    engine = None # Asegúrate de que engine sea None si hay un error para evitar problemas posteriores

Conexión a la base de datos establecida exitosamente.

In [78]:
df_autos

,id,title,link,tag,image,fuel,location,price,brand,year,advertiser,category,subcategory,transmission,slug,fecha
0,1854752,volkswagen gol sedán 2021,https://neoauto.com/venta-de-autos-nuevosauto/...,Seminuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Paulo Soto,autos,Sedán,Mecánica,auto/seminuevo/volkswagen-gol-sedan-2021-1854752,2025-11-27 20:06:48.673453
1,1857469,jeep grand cherokee limited 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,Premium,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Auto Traders,autos,Camioneta,Automática - Secuencial,auto/seminuevo/jeep-grand-cherokee-limited-202...,2025-11-27 20:06:48.673453
2,1856331,hyundai tucson 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,Ocasión,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Diego Atoche,autos,Camioneta,Automática,auto/seminuevo/hyundai-tucson-2020-1856331,2025-11-27 20:06:48.673453
3,1817540,mercedes benz amg sl 55 4matic+ 2022,https://neoauto.com/venta-de-autos-nuevosauto/...,Como nuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,sebastian de souza,autos,Deportivo,Automática - Secuencial,auto/seminuevo/mercedes-benz-amg-sl-55-4matic-...,2025-11-27 20:06:48.673453
4,1852040,ford escape 2017,https://neoauto.com/venta-de-autos-nuevosauto/...,Seminuevo,https://cdn.neoauto.com/elements/autos_usados/...,Gasolina,"Lima, Lima",13900.0,FORD,2017,Auto Summit San Isidro,autos,Camioneta,Automática - Secuencial,auto/seminuevo/ford-escape-2017-1852040,2025-11-27 20:06:48.673453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4002,1854166,suzuki ertiga 2015,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Geyler Diaz Rivera,autos,Vans,Automática,auto/usado/suzuki-ertiga-2015-1854166,2025-11-27 20:06:48.673453
4003,1856680,mg zs 2018,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",10000.0,MG,2018,Jenniffer Cano,autos,Camioneta,Automática - Secuencial,auto/usado/mg-zs-2018-1856680,2025-11-27 20:06:48.673453
4004,1857073,chevrolet tracker 2024,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Miguel Angel Bernal,autos,Camioneta,Automática,auto/usado/chevrolet-tracker-2024-1857073,2025-11-27 20:06:48.673453
4005,1853868,toyota corolla 2016,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Gasolina,"Callao, Callao",13700.0,TOYOTA,2016,Edgar Castro,autos,Sedán,Automática,auto/usado/toyota-corolla-2016-1853868,2025-11-27 20:06:48.673453
4006,1856188,dfsk glory 580 2020,https://neoauto.com/venta-de-autos-nuevosauto/...,None,https://cdn.neoauto.com/static/neoauto3/img/al...,Dual,"Lima, Lima",15000.0,DFSK,2020,Gustavo guzmán guzmán mazuelos,autos,Camioneta,Automática - Secuencial,auto/usado/dfsk-glory-580-2020-1856188,2025-11-27 20:06:48.673453

In [79]:
df_autos.to_csv('autos.csv',header=None)

# ANALIZAMOS TIPOS DE DATOS Y DATA INNECESARIA

In [80]:
df_autos.dtypes

id                       int64
title                   object
link                    object
tag                     object
image                   object
fuel                    object
location                object
price                  float64
brand                   object
year                     int64
advertiser              object
category                object
subcategory             object
transmission            object
slug                    object
fecha           datetime64[ns]
dtype: object

In [81]:
df_clean = df_autos[['fuel','location','price','brand','year','subcategory','transmission']]
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
1,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Camioneta,Automática - Secuencial
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
3,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,Deportivo,Automática - Secuencial
4,Gasolina,"Lima, Lima",13900.0,FORD,2017,Camioneta,Automática - Secuencial
...,...,...,...,...,...,...,...
4002,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Vans,Automática
4003,Gasolina,"Lima, Lima",10000.0,MG,2018,Camioneta,Automática - Secuencial
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática
4005,Gasolina,"Callao, Callao",13700.0,TOYOTA,2016,Sedán,Automática
4006,Dual,"Lima, Lima",15000.0,DFSK,2020,Camioneta,Automática - Secuencial

In [82]:
df_clean = df_clean[df_clean['location'] == 'Lima, Lima']

In [83]:
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
1,Gasolina,"Lima, Lima",30990.0,JEEP,2020,Camioneta,Automática - Secuencial
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
3,Gasolina,"Lima, Lima",279000.0,MERCEDES BENZ,2022,Deportivo,Automática - Secuencial
4,Gasolina,"Lima, Lima",13900.0,FORD,2017,Camioneta,Automática - Secuencial
...,...,...,...,...,...,...,...
4001,Gasolina,"Lima, Lima",10500.0,SUZUKI,2026,Camioneta,Automática - Secuencial
4002,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Vans,Automática
4003,Gasolina,"Lima, Lima",10000.0,MG,2018,Camioneta,Automática - Secuencial
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática
4006,Dual,"Lima, Lima",15000.0,DFSK,2020,Camioneta,Automática - Secuencial

In [84]:
df_clean = df_clean[df_clean['transmission'] != 'Automática - Secuencial']

In [85]:
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
5,Eléctrico,"Lima, Lima",99900.0,BMW,2023,Camioneta,Automática
6,Gasolina,"Lima, Lima",15900.0,DODGE,2018,Camioneta,Automática
7,Gasolina,"Lima, Lima",27990.0,MAZDA,2024,Camioneta,Automática
...,...,...,...,...,...,...,...
3996,Gasolina,"Lima, Lima",1500.0,NISSAN,2003,Hatchback,Automática
3997,Gasolina,"Lima, Lima",17500.0,HYUNDAI,2020,Camioneta,Automática
3998,Gasolina,"Lima, Lima",50000.0,AUDI,2021,Sedán,Automática
4002,Gasolina,"Lima, Lima",11000.0,SUZUKI,2015,Vans,Automática
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática

In [86]:
df_clean['subcategory'].value_counts()

subcategory
Camioneta        1123
Sedán             403
Hatchback         219
Pick Up           143
Vans              126
Deportivo          53
Station Wagon      12
Name: count, dtype: int64

In [89]:
df_clean = df_clean[df_clean['subcategory'].isin(['Camioneta', 'Sedán'])]

In [90]:
df_clean

,fuel,location,price,brand,year,subcategory,transmission
0,Gasolina,"Lima, Lima",10900.0,VOLKSWAGEN,2021,Sedán,Mecánica
2,Gasolina,"Lima, Lima",19900.0,HYUNDAI,2020,Camioneta,Automática
5,Eléctrico,"Lima, Lima",99900.0,BMW,2023,Camioneta,Automática
6,Gasolina,"Lima, Lima",15900.0,DODGE,2018,Camioneta,Automática
7,Gasolina,"Lima, Lima",27990.0,MAZDA,2024,Camioneta,Automática
...,...,...,...,...,...,...,...
3992,Gasolina,"Lima, Lima",16500.0,JETOUR,2023,Camioneta,Automática
3993,Dual,"Lima, Lima",14800.0,SUZUKI,2022,Camioneta,Automática
3997,Gasolina,"Lima, Lima",17500.0,HYUNDAI,2020,Camioneta,Automática
3998,Gasolina,"Lima, Lima",50000.0,AUDI,2021,Sedán,Automática
4004,Gasolina,"Lima, Lima",18500.0,CHEVROLET,2024,Camioneta,Automática

In [91]:
df_clean['fuel'].value_counts()

fuel
Gasolina            1132
Dual                 167
Gas GLP               68
Gasolina-Híbrido      45
Gas GNV               34
Diesel                28
Híbrido               26
Eléctrico             19
Gas                    7
Name: count, dtype: int64

In [93]:
df_clean = df_clean[df_clean['fuel'].isin(['Gasolina', 'Dual'])]

In [94]:
df_clean

          fuel    location    price       brand  year subcategory transmission
0     Gasolina  Lima, Lima  10900.0  VOLKSWAGEN  2021       Sedán     Mecánica
2     Gasolina  Lima, Lima  19900.0     HYUNDAI  2020   Camioneta   Automática
6     Gasolina  Lima, Lima  15900.0       DODGE  2018   Camioneta   Automática
7     Gasolina  Lima, Lima  27990.0       MAZDA  2024   Camioneta   Automática
8     Gasolina  Lima, Lima   7900.0  VOLKSWAGEN  2015       Sedán     Mecánica
...        ...         ...      ...         ...   ...         ...          ...
3992  Gasolina  Lima, Lima  16500.0      JETOUR  2023   Camioneta   Automática
3993      Dual  Lima, Lima  14800.0      SUZUKI  2022   Camioneta   Automática
3997  Gasolina  Lima, Lima  17500.0     HYUNDAI  2020   Camioneta   Automática
3998  Gasolina  Lima, Lima  50000.0        AUDI  2021       Sedán   Automática
4004  Gasolina  Lima, Lima  18500.0   CHEVROLET  2024   Camioneta   Automática

[1299 rows x 7 columns]

In [96]:
df_clean.to_csv('autos_usados_clean.csv',index=None)

### ANALIZAMOS NULOS Y DUPLICADOS

In [97]:
df_clean.isnull().sum()

fuel            0
location        0
price           0
brand           0
year            0
subcategory     0
transmission    0
dtype: int64

In [ ]:
df_clean.dropna(inplace=True)

/tmp/ipython-input-1832953665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.dropna(inplace=True)

In [ ]:
df_clean.isnull().sum()

fuel            0
location        0
price           2
brand           0
year            0
subcategory     0
transmission    0
dtype: int64

In [98]:
df_clean.duplicated().sum()

np.int64(36)

In [99]:
df_clean.drop_duplicates(inplace=True,keep='first')

/tmp/ipython-input-1033133614.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop_duplicates(inplace=True,keep='first')

In [100]:
df_clean

          fuel    location    price       brand  year subcategory transmission
0     Gasolina  Lima, Lima  10900.0  VOLKSWAGEN  2021       Sedán     Mecánica
2     Gasolina  Lima, Lima  19900.0     HYUNDAI  2020   Camioneta   Automática
6     Gasolina  Lima, Lima  15900.0       DODGE  2018   Camioneta   Automática
7     Gasolina  Lima, Lima  27990.0       MAZDA  2024   Camioneta   Automática
8     Gasolina  Lima, Lima   7900.0  VOLKSWAGEN  2015       Sedán     Mecánica
...        ...         ...      ...         ...   ...         ...          ...
3992  Gasolina  Lima, Lima  16500.0      JETOUR  2023   Camioneta   Automática
3993      Dual  Lima, Lima  14800.0      SUZUKI  2022   Camioneta   Automática
3997  Gasolina  Lima, Lima  17500.0     HYUNDAI  2020   Camioneta   Automática
3998  Gasolina  Lima, Lima  50000.0        AUDI  2021       Sedán   Automática
4004  Gasolina  Lima, Lima  18500.0   CHEVROLET  2024   Camioneta   Automática

[1263 rows x 7 columns]

### ANALIZAMOS LAS VARIABLES CATEGORICAS

In [101]:
# GASOLINA
df_clean['fuel'].value_counts()

fuel
Gasolina    1099
Dual         164
Name: count, dtype: int64

In [ ]:
def map_fuel_type(fuel_type):
    if fuel_type == 'Gasolina':
        return 'gasolina'
    else:
        return 'otro'

df_clean['fuel'] = df_clean['fuel'].apply(map_fuel_type)
df_clean['fuel'].value_counts()

/tmp/ipython-input-2870578674.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['fuel'] = df_clean['fuel'].apply(map_fuel_type)

fuel
gasolina    2919
otro         982
Name: count, dtype: int64

In [ ]:
df_clean['location'].value_counts()

location
Lima, Lima                      3489
Arequipa, Arequipa               125
Trujillo, La Libertad             54
Callao, Callao                    35
Piura, Piura                      30
Chiclayo, Lambayeque              23
Cusco, Cusco                      17
Huancayo, Junin                   13
Ica, Ica                          12
Huaraz, Ancash                     8
Chincha, Ica                       8
Tacna, Tacna                       7
Santa, Ancash                      7
Cajamarca, Cajamarca               6
Huanuco, Huanuco                   6
Huamanga, Ayacucho                 5
Huaura, Lima                       4
Cañete, Lima                       3
Islay, Arequipa                    3
Huaral, Lima                       3
San Martin, San Martin             2
Tumbes, Tumbes                     2
Leoncio Prado, Huanuco             2
Pasco, Pasco                       2
Barranca, Lima                     2
Chepen, La Libertad                2
Lambayeque, Lambayeque             2
Pisco, Ica                         2
Puno, Puno                         2
Mariscal Nieto, Moquegua           2
Sechura, Piura                     1
Chanchamayo, Junin                 1
Calca, Cusco                       1
Jaen, Cajamarca                    1
El Dorado, San Martin              1
Caraveli, Arequipa                 1
Nazca, Ica                         1
Yauli, Junin                       1
Chumbivilcas, Cusco                1
Espinar, Cusco                     1
Viru, La Libertad                  1
Pacasmayo, La Libertad             1
Mariscal Caceres, San Martin       1
Huari, Ancash                      1
Concepcion, Junin                  1
Ambo, Huanuco                      1
Sullana, Piura                     1
Abancay, Apurimac                  1
Coronel Portillo, Ucayali          1
Talara, Piura                      1
Paita, Piura                       1
Moyobamba, San Martin              1
San Ignacio, Cajamarca             1
Name: count, dtype: int64

In [ ]:
def map_location_type(location):
    if location == 'Lima, Lima':
        return 'lima'
    else:
        return 'provincia'

df_clean['location'] = df_clean['location'].apply(map_location_type)
df_clean['location'].value_counts()

/tmp/ipython-input-3055761826.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['location'] = df_clean['location'].apply(map_location_type)

location
lima         3489
provincia     412
Name: count, dtype: int64

In [ ]:
# marcas
df_clean['brand'].value_counts()

brand
BMW           359
TOYOTA        313
VOLKSWAGEN    248
MAZDA         208
NISSAN        204
             ...
HAFEI           1
DATSUN          1
JINBEI          1
JMC             1
BAW             1
Name: count, Length: 70, dtype: int64

In [102]:
df_clean.drop(columns=['brand','location'], inplace=True)
df_clean.head()

/tmp/ipython-input-3197811511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(columns=['brand','location'], inplace=True)

       fuel    price  year subcategory transmission
0  Gasolina  10900.0  2021       Sedán     Mecánica
2  Gasolina  19900.0  2020   Camioneta   Automática
6  Gasolina  15900.0  2018   Camioneta   Automática
7  Gasolina  27990.0  2024   Camioneta   Automática
8  Gasolina   7900.0  2015       Sedán     Mecánica

In [103]:
# year
df_clean['year'].dtype

dtype('int64')

In [104]:
#subcategory
df_clean['subcategory'].value_counts()

subcategory
Camioneta    923
Sedán        340
Name: count, dtype: int64

In [105]:
def map_subcategory_type(subcategory):
    if subcategory == 'Camioneta':
        return 'camioneta'
    elif subcategory == 'Sedán':
        return 'sedan'
    else:
        return 'otros'

df_clean['subcategory'] = df_clean['subcategory'].apply(map_subcategory_type)
df_clean['subcategory'].value_counts()

/tmp/ipython-input-780997633.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['subcategory'] = df_clean['subcategory'].apply(map_subcategory_type)

subcategory
camioneta    923
sedan        340
Name: count, dtype: int64

In [106]:
# transmission
df_clean['transmission'].value_counts()

transmission
Automática    865
Mecánica      398
Name: count, dtype: int64

In [107]:
def map_transmission_type(transmission):
    if transmission == 'Automática - Secuencial':
        return 'secuencial'
    elif transmission == 'Automática':
        return 'automatica'
    else:
        return 'mecanica'

df_clean['transmission'] = df_clean['transmission'].apply(map_transmission_type)
df_clean['transmission'].value_counts()

/tmp/ipython-input-875588382.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['transmission'] = df_clean['transmission'].apply(map_transmission_type)

transmission
automatica    865
mecanica      398
Name: count, dtype: int64

In [108]:
df_clean

          fuel    price  year subcategory transmission
0     Gasolina  10900.0  2021       sedan     mecanica
2     Gasolina  19900.0  2020   camioneta   automatica
6     Gasolina  15900.0  2018   camioneta   automatica
7     Gasolina  27990.0  2024   camioneta   automatica
8     Gasolina   7900.0  2015       sedan     mecanica
...        ...      ...   ...         ...          ...
3992  Gasolina  16500.0  2023   camioneta   automatica
3993      Dual  14800.0  2022   camioneta   automatica
3997  Gasolina  17500.0  2020   camioneta   automatica
3998  Gasolina  50000.0  2021       sedan   automatica
4004  Gasolina  18500.0  2024   camioneta   automatica

[1263 rows x 5 columns]

In [109]:
df_clean.to_csv('autos_clean.csv',index=None)